language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/j_external_pcint_library/j_external_pcint_library.ino

install:
    - pip install -U platformio
    - pio upgrade
    - pio lib install https://github.com/EnviroDIY/EnableInterrupt.git
    - pio update

script:
- platformio ci --lib="." --board=mayfly --board=feather32u4 --board=adafruit_feather_m0_usb
