#!/bin/sh

# Script modified from scripts by Jeroen de Bruijn, thephez, and Adafruit
# https://gist.github.com/vidavidorra/548ffbcdae99d752da02
# https://github.com/thephez/doxygen-travis-build
# https://learn.adafruit.com/the-well-automated-arduino-library/travis-ci

# Exit with nonzero exit code if anything fails
set -e

cd $TRAVIS_BUILD_DIR/code_docs/m.css
echo 'Update the style sheets'
cd $TRAVIS_BUILD_DIR/code_docs/m.css/css/EnviroDIY
python $TRAVIS_BUILD_DIR/code_docs/m.css/css/postprocess.py "m-EnviroDIY.css"
python $TRAVIS_BUILD_DIR/code_docs/m.css/css/postprocess.py "m-EnviroDIY.css" "m-documentation.css" -o "m-EnviroDIY+documentation.compiled.css"
python $TRAVIS_BUILD_DIR/code_docs/m.css/css/postprocess.py "m-EnviroDIY.css" "m-theme-EnviroDIY.css" "m-documentation.css" --no-import -o "m-EnviroDIY.documentation.compiled.css"
cp $TRAVIS_BUILD_DIR/code_docs/m.css/css/EnviroDIY/m-EnviroDIY+documentation.compiled.css $TRAVIS_BUILD_DIR/code_docs/Arduino-SDI-12/docs/css

echo 'Creating dox files from example read-me files'
cd $TRAVIS_BUILD_DIR/code_docs/Arduino-SDI-12/docs
python documentExamples.py

echo 'Current Doxygen version...'
$TRAVIS_BUILD_DIR/doxygen-src/build/bin/doxygen -v 2>&1

# Redirect both stderr and stdout to the log file AND the console.
echo 'Generating Doxygen code documentation...'
$TRAVIS_BUILD_DIR/doxygen-src/build/bin/doxygen Doxyfile 2>&1 | tee doxygen.log

echo 'Fixing errant xml section names in examples as generated by Doxygen...'
python fixXmlExampleSections.py

python $TRAVIS_BUILD_DIR/code_docs/m.css/documentation/doxygen.py "mcss-conf.py" --no-doxygen --output mcss.log --templates "$TRAVIS_BUILD_DIR/code_docs/m.css/documentation/templates/EnviroDIY" --debug > mcss-doxy-output.log
